#include "button.h"

void button_init(void)	{
	RCC->HAB2ENR |= RCC_AHB2ENR_GPIOCEN;
	GPIOC->MODER = (GPIOC->MODER & ~GPIOC_MODER_MODE13_Msk) | GPIOC_MODER_MODE13;
	SYSCFG->EXTICR4 = (SYSCFG->EXTICR4 & ~SYSCFG_EXTI4_EXTI13_Msk) | SYSCFG_EXTICR4_EXTI13_PC;
}
